const PartidasPresupuestales = [
    { value: '21101 - Consumibles de oficina', label: '21101 - Consumibles de oficina' },
    { value: '21102 - Útiles, artículos, equipos y herramientas menores de oficina', label: '21102 - Útiles, artículos, equipos y herramientas menores de oficina' },
    { value: '21103 - Papelería', label: '21103 - Papelería' },
    { value: '21201 - Materiales y útiles de impresión y reproducción', label: '21201 - Materiales y útiles de impresión y reproducción' },
    { value: '21401 - Material de limpieza y mantenimiento e insumos para equipos de tecnología de la información y comunicaciones', label: '21401 - Material de limpieza y mantenimiento e insumos para equipos de tecnología de la información y comunicaciones' },
    { value: '21402 - Útiles y equipos menores de tecnología de la información y comunicaciones', label: '21402 - Útiles y equipos menores de tecnología de la información y comunicaciones' },
    { value: '21501 - Publicaciones impresas', label: '21501 - Publicaciones impresas' },
    { value: '21601 - Material de limpieza', label: '21601 - Material de limpieza' },
    { value: '21701 - Material y útiles de enseñanza', label: '21701 - Material y útiles de enseñanza' },
    { value: '21801 - Formas valoradas y papelería oficial', label: '21801 - Formas valoradas y papelería oficial' },
    { value: '22101 - Alimentos para el personal institucional', label: '22101 - Alimentos para el personal institucional' },
    { value: '22301 - Utensilios, materiales y equipos menores para el servicio de alimentación de personas', label: '22301 - Utensilios, materiales y equipos menores para el servicio de alimentación de personas' },
    { value: '24601 - Material eléctrico y electrónico', label: '24601 - Material eléctrico y electrónico' },
    { value: '24701 - Artículos metálicos para la construcción', label: '24701 - Artículos metálicos para la construcción' },
    { value: '24801 - Materiales complementarios', label: '24801 - Materiales complementarios' },
    { value: '25303 - Medicinas y productos farmacéuticos para botiquín institucional', label: '25303 - Medicinas y productos farmacéuticos para botiquín institucional' },
    { value: '25403 - Materiales y suministros médicos para botiquín institucional', label: '25403 - Materiales y suministros médicos para botiquín institucional' },
    { value: '26101 - Combustible', label: '26101 - Combustible' },
    { value: '26102 - Lubricantes y aditivos', label: '26102 - Lubricantes y aditivos' },
    { value: '27101 - Vestuarios y uniformes', label: '27101 - Vestuarios y uniformes' },
    { value: '27201 - Prendas de seguridad y protección personal', label: '27201 - Prendas de seguridad y protección personal' },
    { value: '27301 - Artículos deportivos', label: '27301 - Artículos deportivos' },
    { value: '29101 - Herramientas menores', label: '29101 - Herramientas menores' },
    { value: '29201 - Refacciones y accesorios menores de edificios', label: '29201 - Refacciones y accesorios menores de edificios' },
    { value: '29401 - Refacciones y accesorios menores de equipo de cómputo y tecnologías de la información', label: '29401 - Refacciones y accesorios menores de equipo de cómputo y tecnologías de la información' },
    { value: '29801 - Refacciones y accesorios menores de maquinaria y otros equipos', label: '29801 - Refacciones y accesorios menores de maquinaria y otros equipos' },
    { value: '29901 - Otras refacciones y accesorios menores', label: '29901 - Otras refacciones y accesorios menores' },
    { value: '31101 - Energía eléctrica', label: '31101 - Energía eléctrica' },
    { value: '31201 - Gas', label: '31201 - Gas' },
    { value: '31401 - Telefonía tradicional', label: '31401 - Telefonía tradicional' },
    { value: '31701 - Servicio de internet y redes', label: '31701 - Servicio de internet y redes' },
    { value: '31702 - Servicio de procesamiento de información', label: '31702 - Servicio de procesamiento de información' },
    { value: '31801 - Servicios postales y telegráficos', label: '31801 - Servicios postales y telegráficos' },
    { value: '32201 - Arrendamiento de edificios', label: '32201 - Arrendamiento de edificios' },
    { value: '32302 - Arrendamiento de equipos y bienes de tecnología de la información', label: '32302 - Arrendamiento de equipos y bienes de tecnología de la información' },
    { value: '32501 - Arrendamiento de equipo de transporte', label: '32501 - Arrendamiento de equipo de transporte' },
    { value: '32601 - Arrendamiento de maquinaria, otros equipos y herramientas', label: '32601 - Arrendamiento de maquinaria, otros equipos y herramientas' },
    { value: '32702 - Arrendamiento de licencias de programas de cómputo', label: '32702 - Arrendamiento de licencias de programas de cómputo' },
    { value: '32901 - Otros arrendamientos', label: '32901 - Otros arrendamientos' },
    { value: '33101 - Servicios legales, de contabilidad, auditoría y relacionados', label: '33101 - Servicios legales, de contabilidad, auditoría y relacionados' },
    { value: '33201 - Servicios de diseño, arquitectura, ingeniería y actividades relacionadas', label: '33201 - Servicios de diseño, arquitectura, ingeniería y actividades relacionadas' },
    { value: '33301 - Servicios de consultoría administrativa, procesos, técnica y en tecnologías de la información', label: '33301 - Servicios de consultoría administrativa, procesos, técnica y en tecnologías de la información' },
    { value: '33401 - Servicios de capacitación', label: '33401 - Servicios de capacitación' },
    { value: '33601 - Servicios de apoyo administrativo y secretarial', label: '33601 - Servicios de apoyo administrativo y secretarial' },
    { value: '33603 - Servicios de elaboración e impresión de documentos', label: '33603 - Servicios de elaboración e impresión de documentos' },
    { value: '33801 - Servicios de vigilancia', label: '33801 - Servicios de vigilancia' },
    { value: '33901 - Servicios profesionales, científicos y técnicos integrales', label: '33901 - Servicios profesionales, científicos y técnicos integrales' },
    { value: '34101 - Servicios financieros y bancarios', label: '34101 - Servicios financieros y bancarios' },
    { value: '34501 - Seguro de bienes patrimoniales', label: '34501 - Seguro de bienes patrimoniales' },
    { value: '34701 - Fletes y maniobras', label: '34701 - Fletes y maniobras' },
    { value: '35101 - Conservación y mantenimiento menor de inmuebles', label: '35101 - Conservación y mantenimiento menor de inmuebles' },
    { value: '35201 - Instalación, reparación y mantenimiento de mobiliario y equipo de administración, educacional y recreativo', label: '35201 - Instalación, reparación y mantenimiento de mobiliario y equipo de administración, educacional y recreativo' },
    { value: '35301 - Instalación, reparación y mantenimiento de equipo de cómputo y tecnología de la información', label: '35301 - Instalación, reparación y mantenimiento de equipo de cómputo y tecnología de la información' },
    { value: '35501 - Reparación y mantenimiento de equipo de transporte', label: '35501 - Reparación y mantenimiento de equipo de transporte' },
    { value: '35701 - Instalación, reparación y mantenimiento de maquinaria, otros equipos y herramientas agropecuarias e industriales y equipos especializados', label: '35701 - Instalación, reparación y mantenimiento de maquinaria, otros equipos y herramientas agropecuarias e industriales y equipos especializados' },
    { value: '35801 - Servicios de limpieza y manejo de desechos', label: '35801 - Servicios de limpieza y manejo de desechos' },
    { value: '35901 - Servicios de jardinería y fumigación', label: '35901 - Servicios de jardinería y fumigación' },
    { value: '36202 - Artículos promocionales', label: '36202 - Artículos promocionales' },
    { value: '36601 - Servicio de creación y difusión de contenido exclusivamente a través de internet', label: '36601 - Servicio de creación y difusión de contenido exclusivamente a través de internet' },
    { value: '37101 - Pasajes aéreos nacionales', label: '37101 - Pasajes aéreos nacionales' },
    { value: '37201 - Pasajes terrestres nacionales', label: '37201 - Pasajes terrestres nacionales' },
    { value: '37501 - Viáticos en el país', label: '37501 - Viáticos en el país' },
    { value: '37901 - Otros servicios de traslado y hospedaje', label: '37901 - Otros servicios de traslado y hospedaje' },
    { value: '38201 - Gastos de orden social y cultural', label: '38201 - Gastos de orden social y cultural' },
    { value: '38301 - Congresos y convenciones', label: '38301 - Congresos y convenciones' },
    { value: '39201 - Impuestos y derechos', label: '39201 - Impuestos y derechos' },
    { value: '39801 - Impuesto Sobre Nóminas', label: '39801 - Impuesto Sobre Nóminas' },
    { value: '39902 - Transportación por atención a terceros', label: '39902 - Transportación por atención a terceros' },
    { value: '39903 - Hospedaje por atención a terceros', label: '39903 - Hospedaje por atención a terceros' },
    { value: '39904 - Alimentación por atención a terceros', label: '39904 - Alimentación por atención a terceros' },
    { value: '44201 - Becas y otras ayudas para programas de capacitación', label: '44201 - Becas y otras ayudas para programas de capacitación' },
    { value: '51102 - Anaqueles y estantería', label: '51102 - Anaqueles y estantería' },
    { value: '51501 - Equipo de cómputo y de tecnología de la información', label: '51501 - Equipo de cómputo y de tecnología de la información' },
    { value: '52101 - Equipos y aparatos de proyección de imágenes, audio y video', label: '52101 - Equipos y aparatos de proyección de imágenes, audio y video' },
    { value: '52903 - Instrumentos musicales', label: '52903 - Instrumentos musicales' },
    { value: '54101 - Automóviles y camiones de transporte de personas', label: '54101 - Automóviles y camiones de transporte de personas' },
    { value: '56901 - Otros Equipos', label: '56901 - Otros Equipos' }
    
  ];
  
  export default PartidasPresupuestales;
  